"""Initial migration

Revision ID: 718a68b34fbf
Revises: 06ca7c975679
Create Date: 2025-05-25 22:19:05.544874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718a68b34fbf'
down_revision: Union[str, None] = '06ca7c975679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('analysis_type', sa.Enum('IOC_EXTRACTION', 'RISK_ASSESSMENT', 'ENTITY_RECOGNITION', 'SENTIMENT_ANALYSIS', 'FULL_ANALYSIS', name='analysistype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('extracted_iocs', sa.JSON(), nullable=True),
    sa.Column('extracted_ttps', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('model_parameters', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_status'), 'analysis', ['status'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('NEWS', 'SOCIAL_MEDIA', 'DARK_WEB', 'PASTE_SITE', 'GITHUB', 'LINKEDIN', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('bright_data_config', sa.JSON(), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('last_collection_status', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_enabled'), 'source', ['enabled'], unique=False)
    op.create_index(op.f('ix_source_id'), 'source', ['id'], unique=False)
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=False)
    op.create_index(op.f('ix_source_source_type'), 'source', ['source_type'], unique=False)
    op.create_table('threat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('threat_type', sa.Enum('MALWARE', 'PHISHING', 'VULNERABILITY', 'RANSOMWARE', 'APT', 'OTHER', name='threattype'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('iocs', sa.JSON(), nullable=True),
    sa.Column('ttps', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('related_threats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_severity'), 'threat', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_threat_type'), 'threat', ['threat_type'], unique=False)
    op.create_index(op.f('ix_threat_title'), 'threat', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_title'), table_name='threat')
    op.drop_index(op.f('ix_threat_threat_type'), table_name='threat')
    op.drop_index(op.f('ix_threat_severity'), table_name='threat')
    op.drop_table('threat')
    op.drop_index(op.f('ix_source_source_type'), table_name='source')
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_index(op.f('ix_source_id'), table_name='source')
    op.drop_index(op.f('ix_source_enabled'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_analysis_status'), table_name='analysis')
    op.drop_table('analysis')
    # ### end Alembic commands ###
